### ISSUE TITLE
استفاده از تریلیون بجای تلیارد

### ISSUE THREAD

**Issue by mdbaniani** [Mojtaba118/Persian-Number#3]
با سلام . در پکیج شما بجای عبارت هزار میلیارد از تلیارد؟! استفاده شده که بنظر میرسد نادرست بوده و کلمه تریلیون صحیح باشد. با تشکر از پکیج خوب و زحماتتان

**Comment by Mojtaba118** [comment]
سلام و عرض ادب
نسخه 1.6.0 منتشر شد که این مشکل برطرف شده داخلش
